bulid/lock: bulid/color.o bulid/cursor.o bulid/ytime.o
	touch bulid/lock

bulid/color.o: color.cpp
	g++ -c $^ -o $@

bulid/cursor.o: cursor.cpp
	g++ -c $^ -o $@

bulid/ytime.o: ytime.cpp
	g++ -c $^ -o $@
